### ISSUE TITLE
Sanity.io external data POC!

### ISSUE THREAD

**Issue by vowval** [easyblockshq/easyblocks#31]
External Data with Sanity.io POC would be great!

**Comment by vowval** [comment]
i have used the Shopify idea and modified it to fetch Sanity data, it works well. 

how easyblocks will work with multiple pages?

**Comment by r00dY** [comment]
Hi @vowval, Easyblocks doesn't have a concept of "pages", it is by design to provide maximum flexibility. You can easily build page management on your own and simply connect your page entity with Easyblocks document for visual building.

Please keep in mind that documents are super flexible - they can represent a page, part of page, a single component etc... literally any part of React tree. It's up to you what those documents represent in your product.
